---
- name: install nginx 
  hosts: man
  become: true
  tasks:
      - name: installing nginx
        ansible.builtin.dnf:
          name: nginx
          state: present

      - name: starting nginx service
        ansible.builtin.service:
          name: nginx
          state: started

