---
- name: Use group variables group_vars/all.yaml,group_vars/man.yaml
  hosts: man
  become: true
  tasks:
    - name: "install package {{ pkg_name }}"
      ansible.builtin.dnf:
        name: "{{ pkg_name }}"
        state: present

    - name: "service start and enable"
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
        enabled: true
            
