---
- name: Install nginx only on Amazon Linux.
  hosts: man
  become: true
  gather_facts: true
  tasks:
    - name: get facts and check 
      debug:
        var : ansible_facts

    - name: install on amazon linux only
      dnf:
        name: nginx
        state: present
      when: ansible_facts["distribution"]=="Amazon"    
