---
- name: Start service only if package install changed.
  hosts: man
  become: true
  tasks:
    - name: install Apache 
      dnf:
       name: Apache 
       state: present
      register: Apache_op
    - name: check Apache_op
      debug:
       var: Apache_op
    - name: start service only if changed is true   
      service:
        name: Apache 
        state: restart
      when: Apache_op.changed == True  
