---
- name: shell and command pratice
  hosts: local
  connection: local
  tasks:
      - name: command works directly on target 
        ansible.builtin.command: ls -la
        args:
          chdir: /etc
        register: command_op
      - name: print output of command
        debug:
         var: command_op    
      - name: shell command works on shell on target
        ansible.builtin.shell: ls -la|wc -l
        args:
          chdir: /var/log
                  register: shell_op
      - name: print output of shell
        debug:
         var: shell_op   


           