---
- name: create user if not exist is the work to do
  hosts: man
  become: true
  tasks:
    - name: check if user exists
      command: id roboshop
      register: user_op
      ignore_errors: true
    # - name: check the output of id command
    #   debug:
    #     var: user_op
    - name: create user if not exist    
      user:
        name: roboshop
        shell: /bin/sh
      when: 'no such user' not in user_op.stderr  

